### ISSUE TITLE
image tag

### ISSUE THREAD

**Issue by berkguzel** [gurayyildirim/gepp#7]
Hi, 
I am getting a error for a basic flask app after that section.
```
Deploying apps to Kubernetes
   - Creating a temp container with kubectl.. 
```
### ERROR
 `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create`

Also there are some errors i have, one of them is below.
```
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: guray/gepp-kubectl:v1.18.6")

```
I checked image from dockerhub and image was tagged with `guray/gepp-kubectl:v1.19.0`. Is that could be the reason why i had the error?

**Comment by gurayops** [comment]
Fixed now. Thanks for the issue and correction!
